version: '3'

services:
  agronify:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 20080:4000
    working_dir: /app
    volumes:
      - ./:/app
      - ./google-cloud-key.json:/app/build/google-cloud-key.json
    restart: always
    command: 
     - bash
     - -ec
     - |
       yarn install
       npx prisma generate
       yarn build
       cd build
       node .
       sleep infinity
